# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 06:35
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='mpoly',
        ),
        migrations.AddField(
            model_name='point',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(default='', srid=4326),
            preserve_default=False,
        ),
    ]
