# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 07:36
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0004_mypoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPoint2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(dim=3, srid=4326)),
            ],
        ),
        migrations.AlterField(
            model_name='mypoint',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(srid=32140),
        ),
    ]
