# Generated by Django 2.0 on 2017-12-18 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0006_mypoint3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyPoint',
        ),
        migrations.DeleteModel(
            name='MyPoint2',
        ),
    ]
